#rmarkdown::render("biocondutor-regulatory-genomics-workflow.Rmd", output_format = "all")
rmarkdown::render("biocondutor-regulatory-genomics-workflow.Rmd", output_format = "html_document")
rmarkdown::render("biocondutor-regulatory-genomics-workflow.Rmd", output_format = "word_document")
rmarkdown::render("biocondutor-regulatory-genomics-workflow.Rmd", output_format = "github_document")
rmarkdown::render("biocondutor-regulatory-genomics-workflow.Rmd", output_format = "BiocWorkflowTools::f1000_article")